### ISSUE TITLE
[FEAT] Add vote scene module and Vote view components

### ISSUE THREAD

**Issue by Ekko0701** [Peace-Of-Cookie/Yakgwa-iOS#35]
## Feature Description

- Add vote scene module and Vote view components
## TODO

- [ ] Add VoteScene module
- [ ] Implement date vote views
- [ ] Implement locatino vote views
