### ISSUE TITLE
[FEAT] Implment Splash, Login and Main scene flows

### ISSUE THREAD

**Issue by Ekko0701** [Peace-Of-Cookie/Yakgwa-iOS#37]
## Feature Description
- Implement flows with coordinator

## TODO

- [x] Implement Main tab bar
- [x] Implement splash to login flow
- [x] Implement login to main flow
