### ISSUE TITLE
[FEAT] Implement HomeScene Data, Domain layers 

### ISSUE THREAD

**Issue by Ekko0701** [Peace-Of-Cookie/Yakgwa-iOS#41]
## Feature Description

- Add HomeScene APIs
- Implement business logic
## TODO

- [x] Add `/meets` api 
- [x] Implement Data Layer
- [x] Implement Domain Layer
